server:
  port: 8090

spring:
  application:
    name: app2
  datasource:
    url: jdbc:h2:mem:pocgrpc;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: grpc
    password: grpc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true